In [1]:
import pymongo
from pymongo import MongoClient

In [2]:
client = MongoClient("localhost", 27017) # connect to Mongo Server
db = client.test   # create  database
employee = db.employee  # create table
employee_details = {"Name": "Sonal Parmar", "Address": "101 Heaslip Terrace, Scarborough, ON","Age":"23"}

In [3]:
# insert one record
result = employee.insert_one(employee_details) 

In [4]:
print(result.inserted_id)

664e8d71e0468a0189583688


In [5]:
# insert multiple records
mylist = [{"_id":11,"name":"John","address":"Highway 37"},
          {"_id":12,"name":"Peter","address":"Lowstreet 27"},
          {"_id":13,"name":"Amy","address":"Lowstreet 27"},
          {"_id":14,"name":"Hannah","address":"Mountain 21"},
          {"_id":15,"name":"Michael","address":"Valley 345"},
          {"_id":16,"name": "Vicky", "address": "Lowstreet 27"},
          {"_id":17,"name": "Nicky", "address": "Yellow Garden 23"},
          {"_id":18,"name": "Nancy", "address": "Younge Ave. 123"},
          {"_id":19,"name": "Viola", "address": "Sideway Ave"}]

x = employee.insert_many(mylist) 

BulkWriteError: batch op errors occurred, full error: {'writeErrors': [{'index': 0, 'code': 11000, 'errmsg': 'E11000 duplicate key error collection: test.employee index: _id_ dup key: { _id: 11 }', 'keyPattern': {'_id': 1}, 'keyValue': {'_id': 11}, 'op': {'_id': 11, 'name': 'John', 'address': 'Highway 37'}}], 'writeConcernErrors': [], 'nInserted': 0, 'nUpserted': 0, 'nMatched': 0, 'nModified': 0, 'nRemoved': 0, 'upserted': []}

In [6]:
# list dataBase names
print(client.list_database_names())  

['admin', 'config', 'local', 'test']


In [7]:
# list collection names
print(db.list_collection_names())

['employee']


In [8]:
# fetch all the records
for x in employee.find():
    print(x)

{'_id': ObjectId('664e778506b0f04c789e89fb'), 'Name': 'Sonal Parmar', 'Address': '101 Heaslip Terrace, Scarborough, ON', 'Age': '23'}
{'_id': 1, 'name': 'John', 'address': 'Highway 37'}
{'_id': 2, 'name': 'Peter', 'address': 'Lowstreet 27'}
{'_id': 3, 'name': 'Amy', 'address': 'Close st 652'}
{'_id': 4, 'name': 'Hannah', 'address': 'Mountain 21'}
{'_id': 5, 'name': 'Michael', 'address': 'Valley 345'}
{'_id': 6, 'name': 'Vicky', 'address': 'Yellow Garden 124'}
{'_id': 7, 'name': 'Nicky', 'address': 'Yellow Garden 23'}
{'_id': 8, 'name': 'Nancy', 'address': 'Younge Ave. 123'}
{'_id': 9, 'name': 'Viola', 'address': 'Sideway Ave'}
{'_id': ObjectId('664e7dabfcec6b0939c59539'), 'Name': 'Sonal Parmar', 'Address': '101 Heaslip Terrace, Scarborough, ON', 'Age': '23'}
{'_id': 11, 'name': 'John', 'address': 'Highway 37'}
{'_id': 12, 'name': 'Peter', 'address': 'Lowstreet 27'}
{'_id': 13, 'name': 'Amy', 'address': 'Lowstreet 27'}
{'_id': 14, 'name': 'Hannah', 'address': 'Mountain 21'}
{'_id': 15, 

In [9]:
# fetch top 5 records
myresult = employee.find().limit(5)
for x in myresult:
    print(x)

{'_id': ObjectId('664e778506b0f04c789e89fb'), 'Name': 'Sonal Parmar', 'Address': '101 Heaslip Terrace, Scarborough, ON', 'Age': '23'}
{'_id': 1, 'name': 'John', 'address': 'Highway 37'}
{'_id': 2, 'name': 'Peter', 'address': 'Lowstreet 27'}
{'_id': 3, 'name': 'Amy', 'address': 'Close st 652'}
{'_id': 4, 'name': 'Hannah', 'address': 'Mountain 21'}


In [10]:
# find name and address
for x in employee.find({},{"_id":0,"name":1,"address":1}): 
    print(x)

{}
{'name': 'John', 'address': 'Highway 37'}
{'name': 'Peter', 'address': 'Lowstreet 27'}
{'name': 'Amy', 'address': 'Close st 652'}
{'name': 'Hannah', 'address': 'Mountain 21'}
{'name': 'Michael', 'address': 'Valley 345'}
{'name': 'Vicky', 'address': 'Yellow Garden 124'}
{'name': 'Nicky', 'address': 'Yellow Garden 23'}
{'name': 'Nancy', 'address': 'Younge Ave. 123'}
{'name': 'Viola', 'address': 'Sideway Ave'}
{}
{'name': 'John', 'address': 'Highway 37'}
{'name': 'Peter', 'address': 'Lowstreet 27'}
{'name': 'Amy', 'address': 'Lowstreet 27'}
{'name': 'Hannah', 'address': 'Mountain 21'}
{'name': 'Michael', 'address': 'Valley 345'}
{'name': 'Vicky', 'address': 'Lowstreet 27'}
{'name': 'Nicky', 'address': 'Yellow Garden 23'}
{'name': 'Nancy', 'address': 'Younge Ave. 123'}
{'name': 'Viola', 'address': 'Sideway Ave'}
{}


In [11]:
# find all the fields except Age
for x in employee.find({},{"Age":0}):  
    print(x)

{'_id': ObjectId('664e778506b0f04c789e89fb'), 'Name': 'Sonal Parmar', 'Address': '101 Heaslip Terrace, Scarborough, ON'}
{'_id': 1, 'name': 'John', 'address': 'Highway 37'}
{'_id': 2, 'name': 'Peter', 'address': 'Lowstreet 27'}
{'_id': 3, 'name': 'Amy', 'address': 'Close st 652'}
{'_id': 4, 'name': 'Hannah', 'address': 'Mountain 21'}
{'_id': 5, 'name': 'Michael', 'address': 'Valley 345'}
{'_id': 6, 'name': 'Vicky', 'address': 'Yellow Garden 124'}
{'_id': 7, 'name': 'Nicky', 'address': 'Yellow Garden 23'}
{'_id': 8, 'name': 'Nancy', 'address': 'Younge Ave. 123'}
{'_id': 9, 'name': 'Viola', 'address': 'Sideway Ave'}
{'_id': ObjectId('664e7dabfcec6b0939c59539'), 'Name': 'Sonal Parmar', 'Address': '101 Heaslip Terrace, Scarborough, ON'}
{'_id': 11, 'name': 'John', 'address': 'Highway 37'}
{'_id': 12, 'name': 'Peter', 'address': 'Lowstreet 27'}
{'_id': 13, 'name': 'Amy', 'address': 'Lowstreet 27'}
{'_id': 14, 'name': 'Hannah', 'address': 'Mountain 21'}
{'_id': 15, 'name': 'Michael', 'addres

In [12]:
# fetch recod with given address
data = {"address":'Lowstreet 27'}
mydoc = employee.find(data)
for item in mydoc:
    print(item)

{'_id': 2, 'name': 'Peter', 'address': 'Lowstreet 27'}
{'_id': 12, 'name': 'Peter', 'address': 'Lowstreet 27'}
{'_id': 13, 'name': 'Amy', 'address': 'Lowstreet 27'}
{'_id': 16, 'name': 'Vicky', 'address': 'Lowstreet 27'}


In [13]:
# fetch last 2 docs
mydoc = employee.find(data).limit(-2)
for item in mydoc:
    print(item)

{'_id': 2, 'name': 'Peter', 'address': 'Lowstreet 27'}
{'_id': 12, 'name': 'Peter', 'address': 'Lowstreet 27'}


In [14]:
# fetch all the records where address starts with "Y"
myquery = {"address": {"$regex":"^V"}}
mydoc = employee.find(myquery)
for doc in mydoc:
    print(doc)

{'_id': 5, 'name': 'Michael', 'address': 'Valley 345'}
{'_id': 15, 'name': 'Michael', 'address': 'Valley 345'}


In [15]:
# all the records having "l" in address
myquery = {"address":{"$regex":"l"}} 
mydoc = employee.find(myquery)
for doc in mydoc:
    print(doc)

{'_id': 3, 'name': 'Amy', 'address': 'Close st 652'}
{'_id': 5, 'name': 'Michael', 'address': 'Valley 345'}
{'_id': 6, 'name': 'Vicky', 'address': 'Yellow Garden 124'}
{'_id': 7, 'name': 'Nicky', 'address': 'Yellow Garden 23'}
{'_id': 15, 'name': 'Michael', 'address': 'Valley 345'}
{'_id': 17, 'name': 'Nicky', 'address': 'Yellow Garden 23'}


In [16]:
#address starting with "Y" or "S"
myquery = {"$or":[{"address":{"$regex":"Y"}},{"address":{"$regex":"S"}}]}
mydoc =employee.find(myquery)  
for doc in mydoc:
    print(doc)

{'_id': 6, 'name': 'Vicky', 'address': 'Yellow Garden 124'}
{'_id': 7, 'name': 'Nicky', 'address': 'Yellow Garden 23'}
{'_id': 8, 'name': 'Nancy', 'address': 'Younge Ave. 123'}
{'_id': 9, 'name': 'Viola', 'address': 'Sideway Ave'}
{'_id': 17, 'name': 'Nicky', 'address': 'Yellow Garden 23'}
{'_id': 18, 'name': 'Nancy', 'address': 'Younge Ave. 123'}
{'_id': 19, 'name': 'Viola', 'address': 'Sideway Ave'}


In [17]:
#address starting with "Y" or "S"
myquery = {"address":{"$regex":"^S|^Y"}} 
mydoc =employee.find(myquery)
for doc in mydoc:
    print(doc)

{'_id': 6, 'name': 'Vicky', 'address': 'Yellow Garden 124'}
{'_id': 7, 'name': 'Nicky', 'address': 'Yellow Garden 23'}
{'_id': 8, 'name': 'Nancy', 'address': 'Younge Ave. 123'}
{'_id': 9, 'name': 'Viola', 'address': 'Sideway Ave'}
{'_id': 17, 'name': 'Nicky', 'address': 'Yellow Garden 23'}
{'_id': 18, 'name': 'Nancy', 'address': 'Younge Ave. 123'}
{'_id': 19, 'name': 'Viola', 'address': 'Sideway Ave'}


In [24]:
# find the records where address stras with "Y" and contains "1"
myquery ={"$and":[{"address":{"$regex":"^Y"}},{"address":{"$regex":"1"}}]}
mydoc=employee.find(myquery)
for doc in mydoc:
    print(doc)

{'_id': 6, 'name': 'Vicky', 'address': 'Yellow Garden 124'}
{'_id': 8, 'name': 'Nancy', 'address': 'Younge Ave. 123'}
{'_id': 18, 'name': 'Nancy', 'address': 'Younge Ave. 123'}


In [29]:
# find the records where address stras with "Y" and contains "1" and name starts with "N"
myquery ={"$and":[{"address":{"$regex":"^Y"}},{"address":{"$regex":"1"}},{"name":{"$regex":"^N"}}]}
mydoc=employee.find(myquery)
for doc in mydoc:
    print(doc)

{'_id': 8, 'name': 'Nancy', 'address': 'Younge Ave. 123'}
{'_id': 18, 'name': 'Nancy', 'address': 'Younge Ave. 123'}


In [27]:
# find the records where address stras with "Y" and contains "1" and name != "Vicky"
myquery = {"$and":[{"address":{"$regex":"^Y"}},{"address":{"$regex":"1"}},{"name":{"$ne":"Vicky"}}]}
mydoc = employee.find(myquery)
for doc in mydoc:
    print(doc)

{'_id': 8, 'name': 'Nancy', 'address': 'Younge Ave. 123'}
{'_id': 18, 'name': 'Nancy', 'address': 'Younge Ave. 123'}


In [30]:
# sort the records by "name" column
mydoc = employee.find().sort("name")
for doc in mydoc:
    print(doc)

{'_id': ObjectId('664e778506b0f04c789e89fb'), 'Name': 'Sonal Parmar', 'Address': '101 Heaslip Terrace, Scarborough, ON', 'Age': '23'}
{'_id': ObjectId('664e7dabfcec6b0939c59539'), 'Name': 'Sonal Parmar', 'Address': '101 Heaslip Terrace, Scarborough, ON', 'Age': '23'}
{'_id': ObjectId('664e8d71e0468a0189583688'), 'Name': 'Sonal Parmar', 'Address': '101 Heaslip Terrace, Scarborough, ON', 'Age': '23'}
{'_id': 3, 'name': 'Amy', 'address': 'Close st 652'}
{'_id': 13, 'name': 'Amy', 'address': 'Lowstreet 27'}
{'_id': 4, 'name': 'Hannah', 'address': 'Mountain 21'}
{'_id': 14, 'name': 'Hannah', 'address': 'Mountain 21'}
{'_id': 1, 'name': 'John', 'address': 'Highway 37'}
{'_id': 11, 'name': 'John', 'address': 'Highway 37'}
{'_id': 5, 'name': 'Michael', 'address': 'Valley 345'}
{'_id': 15, 'name': 'Michael', 'address': 'Valley 345'}
{'_id': 8, 'name': 'Nancy', 'address': 'Younge Ave. 123'}
{'_id': 18, 'name': 'Nancy', 'address': 'Younge Ave. 123'}
{'_id': 7, 'name': 'Nicky', 'address': 'Yellow 

In [33]:
# sort the recods based on "name" and "_id"
mydoc = employee.find().sort(["name","_id"])
for doc in mydoc:
    print(doc)

{'_id': ObjectId('664e778506b0f04c789e89fb'), 'Name': 'Sonal Parmar', 'Address': '101 Heaslip Terrace, Scarborough, ON', 'Age': '23'}
{'_id': ObjectId('664e7dabfcec6b0939c59539'), 'Name': 'Sonal Parmar', 'Address': '101 Heaslip Terrace, Scarborough, ON', 'Age': '23'}
{'_id': ObjectId('664e8d71e0468a0189583688'), 'Name': 'Sonal Parmar', 'Address': '101 Heaslip Terrace, Scarborough, ON', 'Age': '23'}
{'_id': 3, 'name': 'Amy', 'address': 'Close st 652'}
{'_id': 13, 'name': 'Amy', 'address': 'Lowstreet 27'}
{'_id': 4, 'name': 'Hannah', 'address': 'Mountain 21'}
{'_id': 14, 'name': 'Hannah', 'address': 'Mountain 21'}
{'_id': 1, 'name': 'John', 'address': 'Highway 37'}
{'_id': 11, 'name': 'John', 'address': 'Highway 37'}
{'_id': 5, 'name': 'Michael', 'address': 'Valley 345'}
{'_id': 15, 'name': 'Michael', 'address': 'Valley 345'}
{'_id': 8, 'name': 'Nancy', 'address': 'Younge Ave. 123'}
{'_id': 18, 'name': 'Nancy', 'address': 'Younge Ave. 123'}
{'_id': 7, 'name': 'Nicky', 'address': 'Yellow 

In [36]:
# Update the address value in one record
myquery ={"address":"Sideway Ave"}
newvalues ={"$set":{"address":"Sideway Ave 123"}}
employee.update_one(myquery,newvalues)
for data in employee.find():
    print(data)

{'_id': ObjectId('664e778506b0f04c789e89fb'), 'Name': 'Sonal Parmar', 'Address': '101 Heaslip Terrace, Scarborough, ON', 'Age': '23'}
{'_id': 1, 'name': 'John', 'address': 'Canyon 123'}
{'_id': 2, 'name': 'Peter', 'address': 'Lowstreet 27'}
{'_id': 3, 'name': 'Amy', 'address': 'Close st 652'}
{'_id': 4, 'name': 'Hannah', 'address': 'Mountain 21'}
{'_id': 5, 'name': 'Michael', 'address': 'Valley 345'}
{'_id': 6, 'name': 'Vicky', 'address': 'Yellow Garden 124'}
{'_id': 7, 'name': 'Nicky', 'address': 'Yellow Garden 23'}
{'_id': 8, 'name': 'Nancy', 'address': 'Younge Ave. 123'}
{'_id': 9, 'name': 'Viola', 'address': 'Sideway Ave 123'}
{'_id': ObjectId('664e7dabfcec6b0939c59539'), 'Name': 'Sonal Parmar', 'Address': '101 Heaslip Terrace, Scarborough, ON', 'Age': '23'}
{'_id': 11, 'name': 'John', 'address': 'Canyon 123'}
{'_id': 12, 'name': 'Peter', 'address': 'Lowstreet 27'}
{'_id': 13, 'name': 'Amy', 'address': 'Lowstreet 27'}
{'_id': 14, 'name': 'Hannah', 'address': 'Mountain 21'}
{'_id': 

In [37]:
# Update the name with "Minnie" where address starts with "C"
myquery ={"address":{"$regex":"^C"}} 
newvalues ={"$set":{"name":"Minnie"}}
mydoc = employee.update_many(myquery,newvalues)
for doc in employee.find():
    print(doc)

{'_id': ObjectId('664e778506b0f04c789e89fb'), 'Name': 'Sonal Parmar', 'Address': '101 Heaslip Terrace, Scarborough, ON', 'Age': '23'}
{'_id': 1, 'name': 'Minnie', 'address': 'Canyon 123'}
{'_id': 2, 'name': 'Peter', 'address': 'Lowstreet 27'}
{'_id': 3, 'name': 'Minnie', 'address': 'Close st 652'}
{'_id': 4, 'name': 'Hannah', 'address': 'Mountain 21'}
{'_id': 5, 'name': 'Michael', 'address': 'Valley 345'}
{'_id': 6, 'name': 'Vicky', 'address': 'Yellow Garden 124'}
{'_id': 7, 'name': 'Nicky', 'address': 'Yellow Garden 23'}
{'_id': 8, 'name': 'Nancy', 'address': 'Younge Ave. 123'}
{'_id': 9, 'name': 'Viola', 'address': 'Sideway Ave 123'}
{'_id': ObjectId('664e7dabfcec6b0939c59539'), 'Name': 'Sonal Parmar', 'Address': '101 Heaslip Terrace, Scarborough, ON', 'Age': '23'}
{'_id': 11, 'name': 'Minnie', 'address': 'Canyon 123'}
{'_id': 12, 'name': 'Peter', 'address': 'Lowstreet 27'}
{'_id': 13, 'name': 'Amy', 'address': 'Lowstreet 27'}
{'_id': 14, 'name': 'Hannah', 'address': 'Mountain 21'}
{

In [38]:
# delete one record with address ="Canyon 123"
db.employee.delete_one({"address":"Canyon 123"}) 

DeleteResult({'n': 1, 'ok': 1.0}, acknowledged=True)

In [40]:
# delete one record with address ="Younge Ave. 123"
myquery = {"address":"Younge Ave. 123"}
employee.delete_one(myquery) 

DeleteResult({'n': 1, 'ok': 1.0}, acknowledged=True)

In [42]:
# delete all the records where address starts with "Y"
myquery ={"address":{"$regex":"^Y"}} 
docs =employee.delete_many(myquery)
print(docs.deleted_count)

3


In [46]:
# delete all the documents
docs = employee.delete_many({})
print("Deleted Documents:",docs.deleted_count)

Deleted Documents: 0


In [49]:
# drop collection name
employee.drop()

In [50]:
print(db.list_collection_names())

[]


# Numpy

In [51]:
import numpy as np

In [52]:
# define array
vecor = np.array([1,2,3])

In [56]:
# access the element from array
vector=np.array([1,2,3,4,5,6])
print(vector[3])

4


In [57]:
# get index of given item
np.where(vector==3)

(array([2], dtype=int64),)

In [59]:
#slicing
vector[1:4]

array([2, 3, 4])

In [60]:
# negative slicing
vector[-5:-2]

array([2, 3, 4])

In [61]:
matrix = np.array([[1,2],[1,2],[1,2]])

In [63]:
matrix[1,1]

2

In [72]:
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
matrix[1:,1:]

array([[5, 6],
       [8, 9]])

In [73]:
# get num of elements in array
matrix.size

9

In [74]:
# shape of an array
matrix.shape

(3, 3)

In [76]:
# dimention of array
matrix.ndim

2

In [78]:
# dot product
vec1 = np.array([1,2,3])
vec2 = np.array([4,5,6])
np.dot(vec1,vec2)

32

In [79]:
# add mat1 and mat2
mat1 = np.array([[1,1,1],[1,1,1],[1,1,2]])
mat2 = np.array([[1,3,1],[1,3,1],[1,3,8]])
np.add(mat1,mat2)

array([[ 2,  4,  2],
       [ 2,  4,  2],
       [ 2,  4, 10]])

In [81]:
# Substract mat1 and mat2
np.subtract(mat1,mat2)

array([[ 0, -2,  0],
       [ 0, -2,  0],
       [ 0, -2, -6]])

In [82]:
# multiply all the corresponding items
mat1*mat2

array([[ 1,  3,  1],
       [ 1,  3,  1],
       [ 1,  3, 16]])

In [83]:
# matrix multiplication
np.matmul(mat1,mat2)

array([[ 3,  9, 10],
       [ 3,  9, 10],
       [ 4, 12, 18]])

In [84]:
# adding an item to matrix
mat1+10

array([[11, 11, 11],
       [11, 11, 11],
       [11, 11, 12]])

In [92]:
mat = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(mat)
add_100 = lambda i: i+100
vectorized_100 = np.vectorize(add_100)
print("Vectorized matrix:\n",vectorized_100(mat))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
Vectorized matrix:
 [[101 102 103]
 [104 105 106]
 [107 108 109]]


In [93]:
mat+100

array([[101, 102, 103],
       [104, 105, 106],
       [107, 108, 109]])